### ISSUE TITLE
[ISSUE] 이슈 PR 타이틀 변경으로 인한 라벨링 자동화 수정

### ISSUE THREAD

**Issue by eundeang** [prgrms-web-devcourse-final-project/WEB1_1_DoItTogether_BE#35]
## 어떤 기능인가요? 
이슈 PR 타이틀 변경으로 인한 라벨링 자동화 수정

## 작업 상세 내용
- [x] labeler 수정

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the .github/labeler.yml file to include PR title-based labeling automation. This change allows for more accurate and flexible labeling based on the PR title content.

You can review changes in this commit: https://github.com/lkilu6456546/prgrms-web-devcourse-final-project-WEB1_1_DoItTogether_BE-35/commit/88bcb9b70b79842af47b0887d9e8c1412410d765.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
